spring:
  application:
    name: api-gateway
    
zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  sensitive-headers:
  routes:
    loan-service:
      path: /loan-service/**
      serviceId: loan-service 
      sensitiveHeaders:
    user-service:
      path: /user-service/**
      serviceId: user-service
      sensitiveHeaders:
    auth-server:
      path: /auth-server/**
      serviceId: auth-server
      sensitiveHeaders:


  
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
      cors:
        allowed-methods:
        - GET
        allowed-origins:
        - "*"



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/
    register-with-eureka: true
    fetch-registry: true   

app:
  security:
    checkTokenUrl: http://localhost:9999/oauth/check_token