server:
    port: 5000    

spring:
  application:
    name: service-discovery   


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/
    register-with-eureka: false
    fetch-registry: false    
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2  